/*
 * JS for Chat generated by Tiggzi
 *
 * Created on: Monday, March 04, 2013, 01:59:20 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '5864b282-eb26-4d76-b066-bbd4a40a5194';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var CameraService = new Tiggr.CameraService({});
var PostGEO = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&lat={lat}&longt={longt}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\"result\":\"success\"}"
});
var UpdatePrefs = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updateprefs.php?topic={newtopic}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var Get2 = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\r\n        \"result\": \"success\"\r\n}"
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
var AddChat = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/addchat.php?userid={userid}&dist={dist}&lat={lat}&longt={longt}&message={message}',
    'dataType': 'json',
    'type': 'get',
});
var GET = new Tiggr.RestService({
    'url': 'http://10.100.31.228/launch/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'jsonp',
    'type': 'get',
});
var UploadFile = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/uploadphoto.php',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
});
var GetInterestsById = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getinterestsbyid.php?userid={userid}',
    'dataType': 'json',
    'type': 'get',
});
var GeolocationService = new Tiggr.GeolocationService({});
var UpdateLocation = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updatelocation.php?lat={latitude}&longt={longt}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var GetUsersOnline = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getusersonline.php',
    'dataType': 'json',
    'type': 'get',
});
var UserAuth = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/userauth.php?email={useremail}',
    'dataType': 'json',
    'type': 'get',
});
var contact = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
var GetChatByLocation = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getchatbylocation.php?userid={userid}&dist={dist}',
    'dataType': 'json',
    'type': 'get',
});
var Getchats = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Profile",
    "location": "Profile.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "ShowInterests",
    "location": "ShowInterests.html"
}, {
    "name": "Chat",
    "location": "Chat.html"
}, {
    "name": "Chat2",
    "location": "Chat2.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];
j_90_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel1_10': 'j_99',
        'NewChat': 'j_97',
        'mobilebutton1_9': 'j_98',
        'mobilegrid_2': 'j_94',
        'mobilegridcell_3': 'j_95',
        'DisplayChats': 'j_96'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_90';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    ShowChats = new Tiggr.DataSource(GetChatByLocation, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_90");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'mobilegrid_2',
            'SET': [{
                'PATH': ['message'],
                'ID': 'DisplayChats',
                'ATTR': '@'
            }]
        }],
        'requestMapping': [{
            'PATH': ['userid'],
            'ATTR': '1'
        }, {
            'PATH': ['dist'],
            'ATTR': '1'
        }]
    });
    datasources.push(ShowChats);
    restservice7 = new Tiggr.DataSource(AddChat, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_90");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['message'],
            'ID': 'NewChat',
            'ATTR': 'value'
        }, {
            'PATH': ['userid'],
            'ATTR': '1'
        }, {
            'PATH': ['lat'],
            'ID': '___local_storage___',
            'ATTR': 'lat'
        }, {
            'PATH': ['longt'],
            'ID': '___local_storage___',
            'ATTR': 'long'
        }, {
            'PATH': ['dist'],
            'ATTR': '10'
        }]
    });
    datasources.push(restservice7);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_90_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_90';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_4675_onLoad = j_90_onLoad = function() {
        screen_4675_elementsExtraJS();
        try {
            ShowChats.execute({})
        } catch (ex) {
            console.log(ex.name + '  ' + ex.message);
            hideSpinner();
        };
        j_90_windowEvents();
        screen_4675_elementsEvents();
    }
    // screen window events
    screen_4675_windowEvents = j_90_windowEvents = function() {
        $('#j_90').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_4675_elementsExtraJS = j_90_elementsExtraJS = function() {
        // screen (screen-4675) extra code
    }
    // screen elements handler
    screen_4675_elementsEvents = j_90_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_93 [name="mobilebutton1_9"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        restservice7.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                }
            },
        });
    }
    $("#j_90").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_90_beforeshow();
    });
    if (runBeforeShow) {
        j_90_beforeshow();
    } else {
        j_90_onLoad();
    }
}
$("#j_90").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_90_js();
});