/*
 * JS for Home generated by Tiggzi
 *
 * Created on: Sunday, March 03, 2013, 09:13:53 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '5864b282-eb26-4d76-b066-bbd4a40a5194';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var CameraService = new Tiggr.CameraService({});
var PostGEO = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&lat={lat}&longt={longt}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\"result\":\"success\"}"
});
var UpdatePrefs = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updateprefs.php?topic={newtopic}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var Get2 = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\r\n        \"result\": \"success\"\r\n}"
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
var GET = new Tiggr.RestService({
    'url': 'http://10.100.31.228/launch/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'jsonp',
    'type': 'get',
});
var UploadFile = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/uploadphoto.php',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
});
var GetInterestsById = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getinterestsbyid.php?userid={userid}',
    'dataType': 'json',
    'type': 'get',
});
var GeolocationService = new Tiggr.GeolocationService({});
var UpdateLocation = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updatelocation.php?lat={latitude}&longt={longt}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var GetUsersOnline = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getusersonline.php',
    'dataType': 'json',
    'type': 'get',
});
var UserAuth = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/userauth.php?email={useremail}',
    'dataType': 'json',
    'type': 'get',
});
var contact = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Profile",
    "location": "Profile.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "ShowInterests",
    "location": "ShowInterests.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];
j_52_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton1_40': 'j_55',
        'mobilelabel1_33': 'j_60',
        'mobilegrid_41': 'j_61',
        'mobilegridcell_42': 'j_62',
        'ShowName': 'j_63',
        'mobilegridcell_43': 'j_64',
        'showingUserID': 'j_65',
        'mobilegridcell_46': 'j_66',
        'mobilebutton1_48': 'j_67',
        'mobilelabel1_6': 'j_57',
        'googlemap1_7': 'j_58',
        'marker1_8': 'j_59',
        'mobilebutton1_49': 'j_68',
        'mobilenavbar2_2': 'j_70',
        'mobilenavbaritem4_3': 'j_71',
        'mobilenavbaritem4_4': 'j_72',
        'mobilenavbaritem4_5': 'j_73'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_52';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    geolocation1 = new Tiggr.DataSource(GeolocationService, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_52");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['coords', 'latitude'],
            'ID': 'googlemap1_7',
            'ATTR': 'latitude'
        }, {
            'PATH': ['coords', 'longitude'],
            'ID': 'googlemap1_7',
            'ATTR': 'longitude'
        }, {
            'PATH': ['coords', 'longitude'],
            'ID': '___local_storage___',
            'ATTR': 'long'
        }, {
            'PATH': ['coords', 'latitude'],
            'ID': '___local_storage___',
            'ATTR': 'lat'
        }],
        'requestMapping': [{
            'PATH': ['options', 'maximumAge'],
            'ATTR': '3000'
        }, {
            'PATH': ['options', 'timeout'],
            'ATTR': '5000'
        }, {
            'PATH': ['options', 'enableHighAccuracy'],
            'ATTR': 'true'
        }, {
            'PATH': ['options', 'watchPosition'],
            'ATTR': 'false'
        }]
    });
    datasources.push(geolocation1);
    restservice3 = new Tiggr.DataSource(UpdateLocation, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_52");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['lat'],
            'ID': '___local_storage___',
            'ATTR': 'lat'
        }, {
            'PATH': ['longt'],
            'ID': '___local_storage___',
            'ATTR': 'long'
        }, {
            'PATH': ['userid'],
            'ID': '___local_storage___',
            'ATTR': 'userID'
        }]
    });
    datasources.push(restservice3);
    restservice4 = new Tiggr.DataSource(GetUsersOnline, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_52");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'mobilegrid_41',
            'SET': [{
                'PATH': ['id'],
                'ID': 'showingUserID',
                'ATTR': '@'
            }, {
                'PATH': ['username'],
                'ID': 'ShowName',
                'ATTR': '@'
            }]
        }],
        'requestMapping': []
    });
    datasources.push(restservice4);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_52_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_52';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_8EAF_onLoad = j_52_onLoad = function() {
        screen_8EAF_elementsExtraJS();
        try {
            geolocation1.execute({})
        } catch (ex) {
            console.log(ex.name + '  ' + ex.message);
            hideSpinner();
        };
        try {
            restservice4.execute({})
        } catch (ex) {
            console.log(ex.name + '  ' + ex.message);
            hideSpinner();
        };
        j_52_windowEvents();
        screen_8EAF_elementsEvents();
    }
    // screen window events
    screen_8EAF_windowEvents = j_52_windowEvents = function() {
        $('#j_52').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_8EAF_elementsExtraJS = j_52_elementsExtraJS = function() {
        // screen (screen-8EAF) extra code
        /* googlemap1_7 */
        var googlemap1_7_options = {
            markerSourceName: "googlemap1_7_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 10,
            showLocationMarker: false
        }
        Tiggzi.__registerComponent('googlemap1_7', new Tiggzi.TiggziMapComponent("googlemap1_7", googlemap1_7_options));
        $("[name='googlemap1_7']").closest("[data-role='page']").bind({
            pageshow: function() {
                if (Tiggzi('googlemap1_7') != undefined) {
                    Tiggzi('googlemap1_7').refresh();
                }
            }
        });
    }
    // screen elements handler
    screen_8EAF_elementsEvents = j_52_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_56 [name="mobilebutton1_49"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        restservice3.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                }
            },
        });
        $('#j_69 [name="mobilenavbaritem4_4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Profile', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_52").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_52_beforeshow();
    });
    if (runBeforeShow) {
        j_52_beforeshow();
    } else {
        j_52_onLoad();
    }
}
$("#j_52").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_52_js();
});