/*
 * JS for Login generated by Tiggzi
 *
 * Created on: Sunday, March 03, 2013, 09:13:53 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '5864b282-eb26-4d76-b066-bbd4a40a5194';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var CameraService = new Tiggr.CameraService({});
var PostGEO = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&lat={lat}&longt={longt}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\"result\":\"success\"}"
});
var UpdatePrefs = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updateprefs.php?topic={newtopic}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var Get2 = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\r\n        \"result\": \"success\"\r\n}"
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
var GET = new Tiggr.RestService({
    'url': 'http://10.100.31.228/launch/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'jsonp',
    'type': 'get',
});
var UploadFile = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/uploadphoto.php',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
});
var GetInterestsById = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getinterestsbyid.php?userid={userid}',
    'dataType': 'json',
    'type': 'get',
});
var GeolocationService = new Tiggr.GeolocationService({});
var UpdateLocation = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updatelocation.php?lat={latitude}&longt={longt}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var GetUsersOnline = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getusersonline.php',
    'dataType': 'json',
    'type': 'get',
});
var UserAuth = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/userauth.php?email={useremail}',
    'dataType': 'json',
    'type': 'get',
});
var contact = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Profile",
    "location": "Profile.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "ShowInterests",
    "location": "ShowInterests.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];
j_0_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel1_2': 'j_4',
        'mobilegrid_16': 'j_16',
        'mobilegridcell_17': 'j_17',
        'mobilegridcell_18': 'j_18',
        'mobileimage_15': 'j_19',
        'mobilegridcell_21': 'j_20',
        'mobilegrid_3': 'j_5',
        'mobilegridcell_4': 'j_6',
        'mobilelabel1_9': 'j_7',
        'mobilegridcell_5': 'j_8',
        'SubmitEmail': 'j_9',
        'mobilegridcell_6': 'j_10',
        'mobilelabel1_11': 'j_11',
        'mobilegridcell_7': 'j_12',
        'PassText': 'j_13',
        'LoginButton': 'j_14',
        'mobilebutton1_14': 'j_15'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_0';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    geolocation2 = new Tiggr.DataSource(GeolocationService, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_0");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['coords', 'latitude'],
            'ID': '___local_storage___',
            'ATTR': 'lat'
        }, {
            'PATH': ['coords', 'longitude'],
            'ID': '___local_storage___',
            'ATTR': 'long'
        }],
        'requestMapping': [{
            'PATH': ['options', 'maximumAge'],
            'ATTR': '3000'
        }, {
            'PATH': ['options', 'timeout'],
            'ATTR': '5000'
        }, {
            'PATH': ['options', 'enableHighAccuracy'],
            'ATTR': 'true'
        }, {
            'PATH': ['options', 'watchPosition'],
            'ATTR': 'false'
        }]
    });
    datasources.push(geolocation2);
    restservice2 = new Tiggr.DataSource(UserAuth, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_0");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['uid'],
            'ID': '___local_storage___',
            'ATTR': 'userID'
        }],
        'requestMapping': [{
            'PATH': ['useremail'],
            'ID': 'SubmitEmail',
            'ATTR': 'value'
        }]
    });
    datasources.push(restservice2);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_0_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_0';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_0256_onLoad = j_0_onLoad = function() {
        screen_0256_elementsExtraJS();
        j_0_windowEvents();
        screen_0256_elementsEvents();
    }
    // screen window events
    screen_0256_windowEvents = j_0_windowEvents = function() {
        $('#j_0').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_0256_elementsExtraJS = j_0_elementsExtraJS = function() {
        // screen (screen-0256) extra code
    }
    // screen elements handler
    screen_0256_elementsEvents = j_0_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_3 [name="LoginButton"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        transition: 'flip',
                        reverse: false
                    });
                    try {
                        restservice2.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                }
            },
        });
    }
    $("#j_0").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_0_beforeshow();
    });
    if (runBeforeShow) {
        j_0_beforeshow();
    } else {
        j_0_onLoad();
    }
}
$("#j_0").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_0_js();
});