/*
 * JS for startScreen generated by Tiggzi
 *
 * Created on: Sunday, March 03, 2013, 09:13:53 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '5864b282-eb26-4d76-b066-bbd4a40a5194';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var CameraService = new Tiggr.CameraService({});
var PostGEO = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&lat={lat}&longt={longt}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\"result\":\"success\"}"
});
var UpdatePrefs = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updateprefs.php?topic={newtopic}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var Get2 = new Tiggr.RestService({
    'url': 'http://10.100.26.245/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'json',
    'type': 'get',
    'echo': "{\r\n        \"result\": \"success\"\r\n}"
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
var GET = new Tiggr.RestService({
    'url': 'http://10.100.31.228/launch/updateprefs.php?userid={userid}&topic={topic}',
    'dataType': 'jsonp',
    'type': 'get',
});
var UploadFile = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/uploadphoto.php',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
});
var GetInterestsById = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getinterestsbyid.php?userid={userid}',
    'dataType': 'json',
    'type': 'get',
});
var GeolocationService = new Tiggr.GeolocationService({});
var UpdateLocation = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/updatelocation.php?lat={latitude}&longt={longt}&userid=1',
    'dataType': 'json',
    'type': 'get',
});
var GetUsersOnline = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/getusersonline.php',
    'dataType': 'json',
    'type': 'get',
});
var UserAuth = new Tiggr.RestService({
    'url': 'http://ec2-50-112-223-94.us-west-2.compute.amazonaws.com/localtalk/userauth.php?email={useremail}',
    'dataType': 'json',
    'type': 'get',
});
var contact = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Profile",
    "location": "Profile.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "ShowInterests",
    "location": "ShowInterests.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];
j_89_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {};
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_89';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_89_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_89';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_3671_onLoad = j_89_onLoad = function() {
        screen_3671_elementsExtraJS();
        j_89_windowEvents();
        screen_3671_elementsEvents();
    }
    // screen window events
    screen_3671_windowEvents = j_89_windowEvents = function() {
        $('#j_89').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_3671_elementsExtraJS = j_89_elementsExtraJS = function() {
        // screen (screen-3671) extra code
    }
    // screen elements handler
    screen_3671_elementsEvents = j_89_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
    }
    $("#j_89").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_89_beforeshow();
    });
    if (runBeforeShow) {
        j_89_beforeshow();
    } else {
        j_89_onLoad();
    }
}
$("#j_89").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_89_js();
});